Update README.md
docker-compose config
   ERROR: The Compose file './docker-compose.yml' is invalid because:
   services.otrecorder.environment contains {"OTR_HOST": "mosquitto"}, which is an invalid type, it should be a string
grep OTR docker-compose.yml
      - OTR_HOST: mosquitto
      - OTR_USER: "user"
      - OTR_PASS: "paass"